language: node_js
node_js:
  - "node"
  - "10"
  - "8"

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - chmod +x ./travis/install.sh
  - ./travis/install.sh
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - npm install -g codecov
  - yarn
  - yarn bootstrap
  - yarn build

script:
  - yarn test

after_success:
  - yarn run cover-upload
  - cat ./libs/quarkit-core/coverage/lcov.info | ./node_modules/.bin/codacy-coverage
  - cat ./libs/quarkit-modules/coverage/lcov.info | ./node_modules/.bin/codacy-coverage
