language: node_js
node_js:
  - "node"
  - "8"
  - "7"
cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn run bootstrap
  - npm install -g codecov
script:
  - yarn run cover
after_success:
  - yarn run cover-upload
  - yarn run codacy-cover-upload
  - find './packages/*/coverage' -name 'lcov.info' -exec cat {} \\;
  - find './packages/*/coverage' -name 'lcov.info' -exec 'cat {} | ./node_modules/.bin/codacy-coverage' \\;