language: node_js
node_js:
  - "node"
  - "7"
cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn run bootstrap
  - npm install -g codecov
script:
  - yarn run cover
after_success:
  - yarn run cover-upload